apiVersion: v1
kind: Service
metadata:
  name: vostra-invoice
  namespace: vostra-invoice-web
spec:
  selector:
    app: vostra-invoice
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
